# Generated by Django 4.2.25 on 2025-12-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status'], 'permissions': (('can_marked_return', 'set book as returned'),)},
        ),
    ]
