# Generated by Django 4.2.25 on 2026-01-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status'], 'permissions': (('can_marked_return', 'set book as returned'), ('can renew', 'change the due back date of book'))},
        ),
    ]
